# -*- coding: utf-8 -*-
"""
Card statistics

Compare the order of a random deck to an ordered deck 
    ([ace, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, ace, 2, 3, ...])
Let 'k' denote the number of times, that this order repeats (usually 4)
Let 'm' denote the length of each cycle (here 13 by default).
    
What is the probability distribution P(N), to be innterpreted as the 
    probability to find the first match after N comparisons?
    
Numerical evaluation shows consistency with an exponential decay.
Best fit paramters vary slgithly with an increase of 'k'.
The case of k=1 allows the conclusion, that the exact distribution may be 
    given by 
    P(N, m) == 1/(m-1) * exp(-1/(m-1) * N) + exp(-1) * delta(N, m+1).
The general case seems to be reasonably well approximated by
    P(N, k, m) ~ alpha(m) * exp(-beta(m) * N) + exp(-k) * delta(N, k*m + 1)
        where 'alpha(m) == 1 / (m - 1)' and 'beta(m) == 1 / (m - 1)'.
        
The parametrization for alpha appears to be exact, even for higher 'k'.
However, for beta the next simplest improvement is to introduce a variable 
    offset 'o(k)', and to redefine beta as 'beta(m, k) == 1 / (m - o(k))'.
    
    Note that o(1) ~ 1, and o(k>>1) ~ 0.5. FIXME: verify!

"""

import numpy as np
from numba import njit
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from matplotlib import rcParams
rcParams["figure.dpi"] = 50


@njit
def _ordered_deck(k:int = 4, m:int = 13):
    """
    Returns an ordered deck of cards as an array. 
    ace == 1, jack == 11, queen == 12, king == 13
    """
    deck = np.arange(m * k) % m
    return deck + 1

@njit
def _shuffled_deck(deck):
    """Returns a shuffled version of the given deck"""
    new_deck = np.copy(deck)
    np.random.shuffle(new_deck)
    return new_deck

@njit
def get_first_match(deck1, deck2):
    """Finds the index (+1) corresponding to the first match"""
    ctr = 0
    for i in range(deck1.shape[0]):
        if deck1[i] == deck2[i]:
            break
        ctr += 1
    return ctr

@njit
def get_distribution(k:int = 4, m:int = 13, size:int = 1000):
    """Generates the distribution of chain lengths"""
    # +1 for 'no match' samples
    dist = np.zeros(k * m + 1, dtype=np.uint32)
    ordered_deck = _ordered_deck(k, m)
    for i in range(size):
        shuffled_deck = _shuffled_deck(ordered_deck)
        match = get_first_match(shuffled_deck, ordered_deck)
        dist[match] += 1
    return dist

def get_distribution_theo(k:int = 4, m:int = 13):
    """Theoretical approximation for the distribution."""
    # offset = 0.96074 +- 0.00242 (a), 0.51107 +- 0.00391 (b) for k=4.
    N = np.arange(1, k*m + 2, 1)
    dist = alpha_m(m, offset=1.0) * np.exp(-beta_m(m, offset=0.5) * N)
    dist[-1] += np.exp(-k)
    return dist

def data_for_histogram(distribution):
    """Converts the distribution to a viable input for np.hist()"""
    size = np.sum(distribution)
    new_dist = np.zeros(size)
    ctr = 0
    for i in range(distribution.shape[0]):
        val = distribution[i]
        new_dist[ctr:ctr + val] = i + 1
        ctr += val
    return new_dist

def get_mean(dist):
    """Computes the expectation value <N> of the given distribution"""
    N = np.arange(1, dist.shape[0] + 1, 1)
    return np.sum(N * dist / np.sum(dist))

def get_var(dist):
    """Computes the variance <N**2> of the given distribution"""
    N_squared = np.arange(1, dist.shape[0] + 1, 1)**2
    var = np.sum(N_squared * dist / np.sum(dist))
    return var - get_mean(dist)**2

def exp_decay(t, alpha:float = 1.0, beta:float = 1.0):
    """Returns the distribution generated by exponential decay."""
    return alpha * np.exp(-beta * t)

def beta_m(m, offset:float = 0.5):
    """Returns the parametrization for beta(m)."""
    return 1 / (m - offset)

def alpha_m(m, offset:float = 1.0):
    """Returns the parametrization for alpha(m)."""
    return 1 / (m - offset)

def fit_exp_decay(k, m, dist):
    """Returs the fit parameters for a modified Poisson distribution."""
    x = np.arange(1, k*m + 1, 1)
    y = dist[:-1] / np.sum(dist)
    par_exp, var_exp = curve_fit(exp_decay, x, y, p0=[0.1, 0.1])
    return par_exp, var_exp
    
def exp_decay_par(k, m, size:int = 10000):
    """Returns the exponential decay parameters as a function of k and m."""
    if type(k) == int:
        print(f"Computing parameters for variable m with k={k}")
        karr = np.full(m.shape, k)
        marr = np.copy(m)
    elif type(m) == int:
        print(f"Computing parameters for variable k with m={m}")
        karr = np.copy(k)
        marr = np.full(k.shape, m)
        
    par = np.zeros((2, karr.shape[0]))
    var = np.zeros((2, karr.shape[0]))
    for i in range(karr.shape[0]):
        dist = get_distribution(karr[i], marr[i], size)
        par_exp, var_exp = fit_exp_decay(karr[i], marr[i], dist)
        par[:, i] = par_exp
        var[0, i] = var_exp[0, 0]
        var[1, i] = var_exp[1, 1]
            
    if not (type(k) == int or type(m) == int):
        print("Computing 2D parameters for variable k and m.")
        par = np.zeros((2, k.shape[0], m.shape[0]))
        var = np.zeros((2, k.shape[0], m.shape[0]))
        for i in range(k.shape[0]):
            for j in range(m.shape[0]):
                dist = get_distribution(k[i], m[i], size)
                par_exp, var_exp = fit_exp_decay(k[i], m[j], dist)
                par[:, i, j] = par_exp
                var[0, i, j] = var_exp[0, 0]
                var[1, i, j] = var_exp[1, 1]
        
    return par, var

def power_law(t, alpha:float = 1.0, beta:float = 1.0):
    """Returns the distribution generated by a power-law."""
    return alpha * t**(-beta)

def plot_alpha_par(mval=13, kmin=1, kmax=20, kstep=1, size=100000):
    """Plots the alpha parameter as a function of m."""
    fig, ax = plt.subplots(1, 1, figsize=(16, 9))
    k = np.arange(kmin, kmax, kstep)
    par, var = exp_decay_par(k=k, m=mval, size=size)
    alpha, beta = par
    sigma_alpha, sigma_beta = np.sqrt(var)
    ax.errorbar(k, alpha, yerr=sigma_alpha, 
                ls='', marker='o', ms=4, mew=1, c='b', 
                label=f'$\\alpha(k, m={mval})$')
    ax.errorbar(k, beta, yerr=sigma_beta, 
                ls='', marker='o', ms=4, mew=1, c='darkorange', 
                label=f'$\\beta(k, m={mval})$')
    ax.legend(fontsize=14)
    fig.tight_layout()
    plt.show()
    
def plot_beta_par(kval=4, mmin=3, mmax=50, mstep=1, size=1000):
    """Plots the beta parameter as a function of m and k."""
    fig, ax = plt.subplots(1, 1, figsize=(16, 9))
    m = np.arange(mmin, mmax, mstep)
    par, var = exp_decay_par(k=kval, m=m, size=size)
    alpha, beta = par
    sigma_alpha, sigma_beta = np.sqrt(var)
    a_offset, var_a_offset = curve_fit(alpha_m, m, alpha, p0=1.0)
    offset, var_offset = curve_fit(beta_m, m, beta, p0=0.5)
    print(f"Offset parameter for alpha(m) is {a_offset[0]} \
          +- {np.sqrt(var_a_offset[0, 0])}")
    print(f"Offset parameter for beta(m) is {offset[0]} \
          +- {np.sqrt(var_offset[0, 0])}")
    ax.errorbar(m, alpha, yerr=sigma_alpha, 
                ls='', marker='o', ms=4, mew=1, c='b', 
                label=f'$\\alpha(k={kval}, m)$')
    ax.errorbar(m, beta, yerr=sigma_beta, 
                ls='', marker='o', ms=4, mew=1, c='darkorange', 
                label=f'$\\beta(k={kval}, m)$')
    ax.plot(m, alpha_m(m, a_offset), c='b', ls='--', lw=1.2, 
            label=f'$\\alpha(m)=\\frac{{1}}{{m-{np.round(*a_offset, 3)}}}$')
    ax.plot(m, beta_m(m, offset), c='darkorange', ls='--', lw=1.2, 
            label=f'$\\beta(m)=\\frac{{1}}{{m-{np.round(*offset, 3)}}}$')
    ax.legend(fontsize=14)
    fig.tight_layout()
    plt.show()   
    

def plot_distribution(k, m, dist):
    """Plots the distribution with the numerical and theoretical fits."""
    # attempts to fit the distribution
    # x = np.arange(1, k*m + 1, 1)
    # y = dist[:-1] / np.sum(dist)
    par_exp, var_exp = fit_exp_decay(k, m, dist)
    alpha_exp, beta_exp = par_exp
    sigma_exp = np.sqrt(var_exp) 
    print(f"Exponential fit with beta = {beta_exp} +- {sigma_exp}")
    print(f"Exponential amplitude is alpha = {alpha_exp} +- {sigma_exp}")
    print()
    # par_pow, var_pow = curve_fit(power_law, x, y, p0=[0.1, 0.6])
    # alpha_pow, beta_pow = par_pow
    # sigma_pow = np.sqrt(var_pow)
    # print(f"Power law fit with beta = {beta_pow} +- {sigma_pow}")
    # print(f"Power law amplitude is alpha = {alpha_pow} +- {sigma_pow}")
    # print()
    
    # visualization
    t = np.linspace(1, k*m + 1, 300)
    label_exp = (r"$\alpha\mathrm{e}^{-\beta t}$ with " + 
                 f"$\\alpha=({np.round(alpha_exp, 4)}\\pm\
                     {np.round(sigma_exp[0, 0], 4)})$ and " + 
                 f"$\\beta=({np.round(beta_exp, 4)}\\pm\
                     {np.round(sigma_exp[1, 1], 4)})$")
    new_dist = data_for_histogram(dist)
    fig, ax = plt.subplots(1, 1, figsize=(16, 9))
    ax.hist(new_dist, bins=k*m, density=True, rwidth=1, 
            color='k', histtype='step', lw=1.5)
    ax.plot(t, exp_decay(t, alpha_exp, beta_exp), c='b', 
            label=label_exp)
    ax.plot(t, exp_decay(t, 1/(m-1), 1/(m-1)), c='b', ls='--') # theory approx
    ax.legend(fontsize=14)
    fig.tight_layout()
    plt.show()

def main():
    k, m, = 4, 13
    size = 1000000
    ordered_deck = _ordered_deck(k, m)
    deck = _shuffled_deck(ordered_deck)
    
    dist = get_distribution(k, m, size)
    dist_theo = get_distribution_theo(k, m)
    checksum = np.sum(dist)
    print(f"Check sum for distribution is {checksum} ({size==checksum}).")
    no_match_expectation = (1 - k/m)**m    # approx exp(-k) for large m
    print(f"Expected probabibility for no match is {no_match_expectation}")
    print(f"Second estimate is {np.exp(-k)} (true value in between?)")
    print(f"Numerical probabibility for no match is {dist[-1] / size}")
    print()
    
    # statistical analysis
    mean = get_mean(dist)
    var = get_var(dist)
    print(f"Numerical chain length is {mean} +- {np.sqrt(var)}")
    mean_theo = get_mean(dist_theo)
    var_theo = get_var(dist_theo)
    print(f"Theoretical chain length is {mean_theo} +- {np.sqrt(var_theo)}")
    print()
    
    # plot_distribution(k, m, dist)
    # plot_alpha_par(mval=13, kmin=1, kmax=2)
    # plot_beta_par(kval=3, mmin=3, mmax=70, size=100000)
    

if __name__ == "__main__":
    main()